version: "3.8"

services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # 挂载nginx服务到容器内
            - ./frontend/dist:/usr/share/nginx/html:ro # 挂载前端服务
        networks:
            - hire-network
        depends_on:
            - backend

    backend:
        build: ./backend
        environment:
            NODE_ENV: production
            PORT: 3001
            DB_HOST: mysql
            DB_USER: appuser
            DB_PASSWORD: User@Secure456!
            DB_DATABASE: hire_data
        ports:
            - "3001:3001"
        networks:
            - hire-network
        depends_on:
            mysql:
                condition: service_healthy
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ROOT@Secure123!
            MYSQL_DATABASE: hire_data
            MYSQL_USER: appuser
            MYSQL_PASSWORD: User@Secure456!
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql/init:/docker-entrypoint-initdb.d
        networks:
            - hire-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 3

networks:
    hire-network:
        driver: bridge

volumes:
    mysql-data:
